// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/tenant": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Busca um tenant no sistema usando o UUID ou o Documento (CNPJ/CPF). Pelo menos um dos dois campos deve ser fornecido.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant"
                ],
                "summary": "Busca um Tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do tenant a ser buscado. (Ex: 8871abf3-ed11-4770-b986-e8d98d022d4f)",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Documento (CNPJ/CPF) do tenant a ser buscado. (Ex: 12345678901234)",
                        "name": "document",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tenant encontrado com sucesso.",
                        "schema": {
                            "$ref": "#/definitions/tenant.TenantResponseDto"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (UUID inválido, ou nenhum dos campos 'uuid'/'document' fornecido).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Tenant não encontrado com os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            },
            "delete": {
                "description": "Exclui permanentemente um tenant no sistema usando o UUID ou o Documento (CNPJ/CPF). Pelo menos um dos dois campos deve ser fornecido.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant"
                ],
                "summary": "Deleta um Tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do tenant a ser excluído. (Ex: 8871abf3-ed11-4770-b986-e8d98d022d4f)",
                        "name": "uuid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Documento (CNPJ/CPF) do tenant a ser excluído. (Ex: 12345678901234)",
                        "name": "document",
                        "in": "query"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Tenant excluído com sucesso (No Content).",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (UUID inválido, ou nenhum dos campos 'uuid'/'document' fornecido).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Tenant não encontrado com os dados fornecidos.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/api/tenant/create": {
            "post": {
                "description": "Cria um novo tenant no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant"
                ],
                "summary": "Cria um novo tenant",
                "parameters": [
                    {
                        "description": "Dados do tenant",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tenant.CreateTenantRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/tenant.TenantResponseDto"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/tenant/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna uma lista paginada de todos os tenants registrados no sistema.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant"
                ],
                "summary": "Lista Tenants",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "O número da página a ser retornada (deve ser \u003e= 1).",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "O número de itens por página (máximo 100).",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de tenants retornada com sucesso.",
                        "schema": {
                            "$ref": "#/definitions/tenant.TenantsResponseDto"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (parâmetros de paginação ausentes ou inválidos, ou pageSize \u003e 100).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/api/tenant/{uuid}": {
            "patch": {
                "description": "Atualiza dados de um tenant existente. O tenant a ser atualizado é identificado pelo UUID no path",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tenant"
                ],
                "summary": "Atualiza um Tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do tenant a ser atualizado.",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos do tenant a serem atualizados. Apenas os campos presentes serão modificados.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tenant.UpdateTenantRequestDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tenant atualizado com sucesso.",
                        "schema": {
                            "$ref": "#/definitions/tenant.TenantResponseDto"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (corpo JSON mal formatado, UUID inválido ou dados de entrada inválidos).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Tenant não encontrado para o UUID fornecido.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "409": {
                        "description": "Conflito (o novo 'document' fornecido já está em uso por outro tenant).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        },
        "/api/user/{identifier}": {
            "post": {
                "description": "Registra um novo usuário no sistema, associado a um tenant (empresa/organização).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Cria um novo Usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identificador (UUID ou Documento) do Tenant ao qual o usuário será associado.",
                        "name": "identifier",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Objeto do usuário que precisa ser criado.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateUserRequestDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário criado com sucesso.",
                        "schema": {
                            "$ref": "#/definitions/user.UserResponseDto"
                        }
                    },
                    "400": {
                        "description": "Requisição inválida (corpo JSON mal formatado, dados de entrada inválidos, ou 'identifier' do tenant ausente).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "404": {
                        "description": "Tenant não encontrado (o 'identifier' fornecido não corresponde a nenhum tenant existente).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "409": {
                        "description": "Conflito (o 'email' fornecido já está em uso).",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    },
                    "500": {
                        "description": "Erro interno do servidor.",
                        "schema": {
                            "$ref": "#/definitions/rest_err.RestErr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest_err.Causes": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "rest_err.RestErr": {
            "type": "object",
            "properties": {
                "causes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest_err.Causes"
                    }
                },
                "code": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "tenant.CreateTenantRequestDto": {
            "type": "object",
            "required": [
                "document",
                "name"
            ],
            "properties": {
                "document": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "tenant.TenantResponseDto": {
            "type": "object",
            "properties": {
                "createAt": {
                    "type": "string"
                },
                "document": {
                    "type": "string"
                },
                "live": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "updateAt": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "tenant.TenantsResponseDto": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "tenants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tenant.TenantResponseDto"
                    }
                }
            }
        },
        "tenant.UpdateTenantRequestDto": {
            "type": "object",
            "properties": {
                "document": {
                    "type": "string"
                },
                "live": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "user.CreateUserRequestDto": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "role": {
                    "$ref": "#/definitions/user.UserRole"
                }
            }
        },
        "user.UserResponseDto": {
            "type": "object",
            "properties": {
                "create_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "live": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/user.UserRole"
                },
                "tenant_uuid": {
                    "type": "string"
                },
                "update_at": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "user.UserRole": {
            "type": "string",
            "enum": [
                "SYSTEM_ADMIN",
                "TENANT_ADMIN",
                "TENANT_USER"
            ],
            "x-enum-varnames": [
                "RoleSystemAdmin",
                "RoleTenantAdmin",
                "RoleTenantUser"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
